### ISSUE TITLE
Hardware requirements?

### ISSUE THREAD

**Issue by ordinary-slim** [JLnorthwestern/GO-MELT#1]
Are there any hardware requirements to run your code? I would guess an NVIDIA GPU is necessary?

PS: I think your paper is very cool!

**Comment by JLnorthwestern** [comment]
Thank you! To answer your questions:
To achieve the maximum performance, an NVIDIA GPU is necessary. However, you can run GO-MELT on a CPU (as we show in the CMAME paper, though we have not tested/tried running on a CPU cluster). From a development side, we typically troubleshoot on the CPU and then run for performance on the GPU. The only real requirement is using JAX, which typically requires a Linux OS (and possibly macOS, I've seen it be done before). If you have a Windows system (like I do), you can set up Windows Subsystem for Linux (WSL) to run GO-MELT.
